import Head from 'next/head'
import Apps from './cytoscapes'
import ResponsiveAppBar from './AppBar'
import { useState } from 'react'
import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
import Value from './value'

export default function Home() {
  const [page, setPage] = useState<number>(0);
  return (
    <>
      <Head>
        <title>StarBiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar/>
      { page === 1 ? 
        <Value/>:
        page === 0 ?
        <Apps/>:
        page === 2 ?
        <></>:
        <></>
      }
      {/* <div style={{backgroundColor:"#1976d2", height:'60.5px', width: '100%', textAlign:'center'}}>
        <ArrowDropDownIcon sx={{fontSize:'90px'}} onClick={(() => setPage(page + 1))} />
      </div> */}
    </>
  )
}
